import Head from 'next/head';
import styled from 'styled-components';
import Layout from '../components/Layout';
import Container from '../components/shared/container/Container.styled';

export default function Home() {
    return (
        <>
            <Head>
                <title>Vherniel Lebis | Web Developer and Designer</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>
            <Layout>
                <Container>
                    <Headline>
                        I’m Vherniel Lebis, a creative web designer and
                        developer. I deliver dynamic, user-friendly, and
                        effective websites with JavaScript.
                    </Headline>
                </Container>
            </Layout>
        </>
    );
}

var Headline = styled.h1`
    font-size: 1.25rem;
    line-height: 1.3;
`;
